[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["macros", "rt-multi-thread", "signal"] }
tonic = "0.11"
prost = "0.12"

[build-dependencies]
tonic-build = "0.11"
